### ISSUE TITLE
Project is compromised

### ISSUE THREAD

**Issue by Outurnate** [mspanish/html_from_json#1]
Just a heads up, looks like a malicious gif file was uploaded in an attempt to compromise your site.  The file can be found [here](https://github.com/mspanish/html_from_json/blob/543d64f57852dbe45ee57ed74d8e41e3def903ba/images/stories/movie.gif)

This would in theory allow an attacker arbitrary code execution

**Comment by mspanish** [comment]
Yikes thanks - that was converted from JOOMLA, what a piece of crap that cms was! h All these files came directly from that site, which was indeed compromised. Thanks again for this - no site is live with this code, but it's here as well as on my HD.
